index.html
Closes issue 11.
@marcoscaceres PTAL?
=> Have an instance of Permissions on Navigator and WorkerNavigator.

index.html, published/FPWD.html
Just discussed with @wseltzer about this :-)
=> Fixes to make pubrules compliant

index.html
This is my first attempt at incorporating mediacapture-permissions.
It has not been tidy'ed yet, since tidy did other changes to the base spec (it would be better if tidying the base spec was a separate PR).
=> Mediacapture permissions

index.html
This PR re-enters the changes that were lost in transition
while entering the addition of the media permissions.
=> Re-entering agreed fixes to Media permissions

index.html
Please take a look. This is related to #60.
=> Add background-sync permission.

index.html
=> Name the query, request, and revoke a permission algorithms.

index.html
https://rawgit.com/jyasskin/permissions/storage-identifier-algorithm/index.html#dfn-get-a-permission-storage-identifier
=> Define the 'get a permission storage identifier' algorithm.

index.bs, index.html
=> Add the "bluetooth" permission, linked to [web-bluetooth].

index.bs
Make the examples a little more 2015... for the millennials.
=> chore(examples): Modernize JS examples

contributing.md
* Don't require updating index.html anymore, since deploy.sh does that.
* Suggest the Karma commit message format.
=> docs(contributing): improve the guidelines for changes

index.bs
Move Permissions Registry just before the Examples section.
=> refactor: move permissions registry (closes #103)

index.bs
This likely needs some review before merging. I added what I thought was the obvious thing to say, and removed some overtaken-by-events materials, but there are enough things linked that I might have some of them wrong.
=> Resolve TODOs on media type permissions

index.bs
Preview at https://api.csswg.org/bikeshed/?url=https://raw.githubusercontent.com/jyasskin/permissions/permissionname-links/index.bs#permission-registry.
=> Link to the Storage spec for persistent-storage's definition

.pr-preview.json
See https://github.com/tobie/pr-preview#pr-preview
=> Add support for pr-preview

index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/foolip/permissions/pull/190.html" title="Last updated on Feb 14, 2019, 10:27 AM UTC (a4c6047)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/permissions/190/bfeafd5...foolip:a4c6047.html" title="Last updated on Feb 14, 2019, 10:27 AM UTC (a4c6047)">Diff</a>
=> Use [SameObject] for navigator.permissions IDL

index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/permissions/pull/238.html" title="Last updated on Apr 21, 2021, 7:11 AM UTC (1726ece)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/permissions/238/62b681f...1726ece.html" title="Last updated on Apr 21, 2021, 7:11 AM UTC (1726ece)">Diff</a>
=> Editorial: cleanup

index.bs
closes #175 
* ❌ WebKit - [rniwa asked for removal](https://github.com/w3c/permissions/issues/175#issuecomment-671553031). 
* ❌Gecko - [not implementing](https://github.com/w3c/permissions/issues/175#issuecomment-645724085) - cc @annevk, for confirmation.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/permissions/pull/246.html" title="Last updated on Jun 17, 2021, 6:05 AM UTC (b0434f5)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/permissions/246/deccd89...b0434f5.html" title="Last updated on Jun 17, 2021, 6:05 AM UTC (b0434f5)">Diff</a>
=> Remove clipboard-write

index.bs
closes #192 
* ✅ Blink 
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/permissions/pull/247.html" title="Last updated on Jul 1, 2021, 6:11 AM UTC (03722d4)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/permissions/247/86e21ca...03722d4.html" title="Last updated on Jul 1, 2021, 6:11 AM UTC (03722d4)">Diff</a>
=> Add 'screen-wake-lock' permission

index.bs
This reverts commit 5c8fc9bb862bc8ffc841aa1a43f566886eaed32c.
Implementation commitment: No one implements this, so removing it.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/permissions/pull/255.html" title="Last updated on Jul 28, 2021, 1:21 AM UTC (df7b79b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/permissions/255/da86e19...df7b79b.html" title="Last updated on Jul 28, 2021, 1:21 AM UTC (df7b79b)">Diff</a>
=> Revert "Add "gamepad" permission (#200)"

index.bs
closes #203
closes #161 
***
[PR Preview](https://github.com/tobie/pr-preview#pr-preview) failed to build. _(Last tried on Jul 26, 2021, 10:02 PM UTC)_.
<details>
<summary>More</summary>
PR Preview relies on a number of web services to run. There seems to be an issue with the following one:
:rotating_light: [CSS Spec Preprocessor](https://api.csswg.org/bikeshed/) - CSS Spec Preprocessor is the web service used to build Bikeshed specs.
:link: [Related URL](https://api.csswg.org/bikeshed/?url=https%3A%2F%2Fraw.githubusercontent.com%2Fw3c%2Fpermissions%2Fe87340adff4e9a012095f482c0b40f7a6ea5fa11%2Findex.bs&force=1&md-warning=not%20ready)
```
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>500 Internal …
```
=> Remove 'device-info' permission

index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/permissions/pull/261.html" title="Last updated on Jul 28, 2021, 10:02 AM UTC (4e1cbb2)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/permissions/261/dce7db7...4e1cbb2.html" title="Last updated on Jul 28, 2021, 10:02 AM UTC (4e1cbb2)">Diff</a>
=> Midi is secure context only 

index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/permissions/pull/260.html" title="Last updated on Aug 2, 2021, 5:27 AM UTC (6a74ca1)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/permissions/260/5e35b9f...6a74ca1.html" title="Last updated on Aug 2, 2021, 5:27 AM UTC (6a74ca1)">Diff</a>
=> Geolocation is secure context only

.github/workflows/auto-publish.yml, index.html
Switching spec back to Respec, as it's easier for me to edit and for me to help others edit.
=> Chore: convert back to ReSpec

index.html
PTAL @jyasskin and @marcoscaceres
***
<a href="https://pr-preview.s3.amazonaws.com/miketaylr/permissions/pull/280.html" title="Last updated on Aug 30, 2021, 7:15 PM UTC (6b795ad)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/permissions/280/f0a3f44...miketaylr:6b795ad.html" title="Last updated on Aug 30, 2021, 7:15 PM UTC (6b795ad)">Diff</a>
=> Fixes #279 - Add myself as editor, mark Jeffrey as emeritus

index.html
closes #275 & #276
r? @marcoscaceres
=> Fixes a couple of typos in the examples

index.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/permissions/pull/313.html" title="Last updated on Nov 4, 2021, 1:37 PM UTC (f8d86bb)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/permissions/313/2d02c47...f8d86bb.html" title="Last updated on Nov 4, 2021, 1:37 PM UTC (f8d86bb)">Diff</a>
=> Editorial: relocate PermissionName/push definition

index.html
r? @marcoscaceres
***
<a href="https://pr-preview.s3.amazonaws.com/miketaylr/permissions/pull/316.html" title="Last updated on Nov 8, 2021, 11:41 PM UTC (5850fff)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/permissions/316/eb23f5d...miketaylr:5850fff.html" title="Last updated on Nov 8, 2021, 11:41 PM UTC (5850fff)">Diff</a>
=> Editorial: relocate midi & ambient-light-sensor powerful features

index.html
Sent https://github.com/w3c/mediacapture-screen-share/pull/196
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/permissions/pull/312.html" title="Last updated on Nov 4, 2021, 4:50 AM UTC (5a7204f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/permissions/312/191a50a...5a7204f.html" title="Last updated on Nov 4, 2021, 4:50 AM UTC (5a7204f)">Diff</a>
=> Relocate screen-capture

index.html
r? @marcoscaceres
***
<a href="https://pr-preview.s3.amazonaws.com/miketaylr/permissions/pull/318.html" title="Last updated on Nov 12, 2021, 10:40 PM UTC (91317ec)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/permissions/318/c3c5605...miketaylr:91317ec.html" title="Last updated on Nov 12, 2021, 10:40 PM UTC (91317ec)">Diff</a>
=> Editorial: relocate background-sync and bluetooth

index.html
PTAL @marcoscaceres
***
<a href="https://pr-preview.s3.amazonaws.com/miketaylr/permissions/pull/324.html" title="Last updated on Nov 18, 2021, 11:14 PM UTC (35723b8)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/permissions/324/2649390...miketaylr:35723b8.html" title="Last updated on Nov 18, 2021, 11:14 PM UTC (35723b8)">Diff</a>
=> Editorial: Relocate "camera", "microphone", "notifications", "speaker-selection".

index.html
=> Editorial: relocate "persistent-storage" powerful feature

index.html
r? @marcoscaceres
***
<a href="https://pr-preview.s3.amazonaws.com/miketaylr/permissions/pull/334.html" title="Last updated on Nov 29, 2021, 7:08 PM UTC (9f6c3af)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/permissions/334/bd9c1b3...miketaylr:9f6c3af.html" title="Last updated on Nov 29, 2021, 7:08 PM UTC (9f6c3af)">Diff</a>
=> Editorial: relocate "background-fetch", "display-capture", "xr"

index.html
"accelerometer", "background-fetch", "display-capture", "gyroscope",
"magnetometer", "xr-spatial-tracking" are all now defined in their
parent specs.
PTAL @marcoscaceres
***
<a href="https://pr-preview.s3.amazonaws.com/miketaylr/permissions/pull/335.html" title="Last updated on Dec 7, 2021, 2:10 PM UTC (c9db65b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/permissions/335/5a81ff1...miketaylr:c9db65b.html" title="Last updated on Dec 7, 2021, 2:10 PM UTC (c9db65b)">Diff</a>
=> Editorial: Relocate more powerful features.

index.html
PTAL @marcoscaceres
***
<a href="https://pr-preview.s3.amazonaws.com/miketaylr/permissions/pull/336.html" title="Last updated on Dec 10, 2021, 3:38 PM UTC (b81b9ea)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/permissions/336/5889e68...miketaylr:b81b9ea.html" title="Last updated on Dec 10, 2021, 3:38 PM UTC (b81b9ea)">Diff</a>
=> Editorial: relocate nfc powerful feature.

index.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/permissions/pull/350.html" title="Last updated on Feb 4, 2022, 3:57 PM UTC (4e02d67)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/permissions/350/29646e0...4e02d67.html" title="Last updated on Feb 4, 2022, 3:57 PM UTC (4e02d67)">Diff</a>
=> Editorial: cleanup examples

index.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/permissions/pull/345.html" title="Last updated on Feb 4, 2022, 3:49 AM UTC (c32a247)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/permissions/345/378b7fd...c32a247.html" title="Last updated on Feb 4, 2022, 3:49 AM UTC (c32a247)">Diff</a>
=> Editorial: clean up abstract

index.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/permissions/pull/351.html" title="Last updated on Feb 9, 2022, 5:28 AM UTC (99e7253)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/permissions/351/29646e0...99e7253.html" title="Last updated on Feb 9, 2022, 5:28 AM UTC (99e7253)">Diff</a>
=> Editorial: clean up Relationship to Permissions Policy

index.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/permissions/pull/357.html" title="Last updated on Feb 9, 2022, 2:42 AM UTC (fcdcf45)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/permissions/357/7e03a6a...fcdcf45.html" title="Last updated on Feb 9, 2022, 2:42 AM UTC (fcdcf45)">Diff</a>
=> Editorial: make 'Creating instances' an algorithm

index.html
Drops a couple of words...
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/permissions/pull/359.html" title="Last updated on Feb 9, 2022, 6:07 AM UTC (56ea546)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/permissions/359/f503804...56ea546.html" title="Last updated on Feb 9, 2022, 6:07 AM UTC (56ea546)">Diff</a>
=> Editorial: generalize statement about PermissionState emum

index.html
Can link to this from the registry as part of the registration instructions...
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/permissions/pull/362.html" title="Last updated on Feb 14, 2022, 9:09 PM UTC (e2872a2)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/permissions/362/cbed850...e2872a2.html" title="Last updated on Feb 14, 2022, 9:09 PM UTC (e2872a2)">Diff</a>
=> Add requirements for specifying Powerful Features

index.html
closes #162 
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/permissions/pull/365.html" title="Last updated on Feb 24, 2022, 7:30 PM UTC (3bc46a1)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/permissions/365/4c4eebc...3bc46a1.html" title="Last updated on Feb 24, 2022, 7:30 PM UTC (3bc46a1)">Diff</a>
=> Handle non-fully-active documents

index.html
closes #283
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/permissions/pull/368.html" title="Last updated on Feb 22, 2022, 7:39 AM UTC (aa23a3c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/permissions/368/88c0638...aa23a3c.html" title="Last updated on Feb 22, 2022, 7:39 AM UTC (aa23a3c)">Diff</a>
=> Editorial: add UA + spec conformance classes

index.html
Based on recent discussions, we note that most (but not all!) powerful features are also policy-controlled features.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/permissions/pull/367.html" title="Last updated on Feb 25, 2022, 12:47 AM UTC (d122c3d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/permissions/367/4c4eebc...d122c3d.html" title="Last updated on Feb 25, 2022, 12:47 AM UTC (d122c3d)">Diff</a>
=> Editorial: clarify Permissions Policy / Powerful Feature overlap

index.html
Couple of tweaks here and there, PTAL @marcoscaceres
***
<a href="https://pr-preview.s3.amazonaws.com/miketaylr/permissions/pull/371.html" title="Last updated on Mar 10, 2022, 11:48 PM UTC (6b7bdda)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/permissions/371/65998c4...miketaylr:6b7bdda.html" title="Last updated on Mar 10, 2022, 11:48 PM UTC (6b7bdda)">Diff</a>
=> Editorial: Do an editorial pass on first 3 sections

index.html
PTAL @marcoscaceres
***
<a href="https://pr-preview.s3.amazonaws.com/miketaylr/permissions/pull/373.html" title="Last updated on Mar 17, 2022, 12:15 AM UTC (5e4d0ba)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/permissions/373/39a5a6f...miketaylr:5e4d0ba.html" title="Last updated on Mar 17, 2022, 12:15 AM UTC (5e4d0ba)">Diff</a>
=> Editorial: take an editorial pass at section 4

index.html
So that variable highlighting on mouse hover works properly.
***
<a href="https://pr-preview.s3.amazonaws.com/thiagowfx/permissions/pull/427.html" title="Last updated on Nov 22, 2023, 3:41 PM UTC (938d446)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/permissions/427/d9f7eda...thiagowfx:938d446.html" title="Last updated on Nov 22, 2023, 3:41 PM UTC (938d446)">Diff</a>
=> Editorial: add <div class="algorithm"> in missing places

index.html
closes #392
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/permissions/pull/400.html" title="Last updated on Nov 25, 2022, 3:22 AM UTC (192ec80)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/permissions/400/5fd60ef...192ec80.html" title="Last updated on Nov 25, 2022, 3:22 AM UTC (192ec80)">Diff</a>
=> Editorial: define permission states consistently
