w3c/permissions

index.html
The Mailing List in the boilerplate says p-webapps and since WebAppSec is now publishing this spec, the list should now say p-webappsec.
=> Boilerplate mail list should be public-webappsec

index.html
This matches the [current Chromium implementation](https://code.google.com/p/chromium/codesearch/#chromium/src/third_party/WebKit/Source/modules/permissions/Permissions.idl), which has a `requestAll()` function to handle a sequence of permissions. A sequence could also be handled with `Promise.all()`, like [`query()` suggests](https://rawgit.com/jyasskin/permissions/no-request-sequence/index.html#h-note1).
=> Make Permissions.request() only take a single descriptor.

index.html
This is now ready to review. See it in action at https://rawgit.com/jyasskin/permissions/allow-choosers/index.html, and a use of the new extension hooks at https://rawgit.com/jyasskin/web-bluetooth-1/permission-api/index.html#permission-api-integration.
=> Let each permission refine its algorithms and store data.

index.html
https://rawgit.com/jyasskin/permissions/storage-type/index.html#idl-def-PermissionStorage
This is separate from the PermissionStatus that gets returned to users and from
the PermissionDescriptor that users query the permission with.
=> Define a PermissionStorage type for each permission to store data with.

index.bs, index.html
This paragraph keeps confusing people, since these functions are in fact specified. Removing the paragraph doesn't guarantee we'll keep the functions: it just makes the spec self-consistent.
=> Remove the incorrect paragraph about request() and revoke() having been removed from the spec.

index.bs, index.html
* permission store
* permission storage identifier
* retrieve the permission storage
* boolean permission
* boolean permission query algorithm
* boolean permission request algorithm
Web Bluetooth is about to use the first 3 of these. It also uses a couple other terms, but I think it's a bug that it needs to, so I don't want to export them.
=> Export dfn-type definitions that other specs should be able to use.

index.bs, index.html
As @domenic requested in #66. See https://rawgit.com/jyasskin/permissions/rename-associated-permission-descriptor/index.html#permission-descriptor-type.
I wanted to use "permission query type", but the type is also used to describe the permission being requested in `request()`, so descriptor fits.
=> Rename the "associated PermissionDescriptor" to the "permission descriptor type".

index.bs, index.html
Like https://storage.spec.whatwg.org/, this spec defines both an API and
common terminology and infrastructure that can underpin other
specifications.
Preview at https://rawgit.com/jyasskin/permissions/retitle/index.html.
I'll also rearrange some of the sections to more clearly separate the API from the infrastructure, but I'd like to be sure the renaming has general agreement first, so I don't need to maintain a reordering in a long-lived branch.
=> Retitle the Permissions spec to emphasize the infrastructure more.

index.bs
This option is the most straightforward about giving the UA nearly complete flexibility. The main constraint is that the result should only change when the UA gets new information about the user's intent, but we don't say what constitutes new information. This version also gives some examples ([media](https://api.csswg.org/bikeshed/?url=https://raw.githubusercontent.com/jyasskin/permissions/ua-can-return-anything/index.bs#media-devices) and [durable storage](https://api.csswg.org/bikeshed/?url=https://raw.githubusercontent.com/jyasskin/permissions/ua-can-return-anything/index.bs#persistent-storage)) of constraining permission behavior further on a per-API basis.
Preview at https://api.csswg.org/bikeshed/?url=https://raw.githubusercontent.com/jyasskin/permissions/ua-can-return-anything/inde …
=> Give the UA permission to return anything it wants from query().

index.bs
This text is redundant: the IDL already states this.
=> chore(navigator-and-workernavigator-extension): remove redudant text

index.bs
These were lost in the Bikeshed conversion because I didn't realize
Bikeshed let us specify them (tabatkins/bikeshed#362).
@marcoscaceres
=> chore(editors): add W3C editor IDs

index.bs
By default, features will always be "denied" in non-secure contexts. The
"allowed in non-secure contexts" flag undoes this default.
It would be possible to throw an exception from request() and possibly
query() when a secure-only feature is used from a non-secure context,
but denying leads to one fewer behavior that developers need to account
for.
Preview at https://api.csswg.org/bikeshed/?url=https://raw.githubusercontent.com/jyasskin/permissions/secure-permissions/index.bs#requires-a-secure-context
@mikewest
=> feat(registry): features require a secure context by default, with opt-out

index.bs
Instead of forcing specs for simple permissions to write out a permission
descriptor. This partially fixes @annevk's objection that writing `{name: "persistent-storage"}` in a spec doesn't formally create a WebIDL dictionary instance, although we'll still need to formalize syntax like that for more complicated descriptors.
Preview at https://api.csswg.org/bikeshed/?url=https://raw.githubusercontent.com/jyasskin/permissions/permission-name-shorthand/index.bs#reading-current-states. I'm not sure the best place to define this. I want folks who click the link to, say, https://api.csswg.org/bikeshed/?url=https://raw.githubusercontent.com/jyasskin/permissions/permission-name-shorthand/index.bs#request-permission-to-use to find the definitions of the shorthands (so a separate "shorthands" …
=> feat(algorithms): allow calling with a PermissionName

index.bs
The issue was based on a misunderstanding; there are many reasons
why a getUserMedia call can fail.
=> Resolve "issue-media-granted"

.travis.yml
Prevent TR from becoming more TRash.
=> feat(travis): autopublish with echidna (closes #24)

index.bs
"Permission state" and "extra permission data" didn't explicitly say
that features could constrain them, or give features a clear place to do
it. This commit fixes that.
Preview at https://api.csswg.org/bikeshed/?url=https://github.com/jyasskin/permissions/raw/delegate-to-permission-state/index.bs#permission-state-constraints
=> feat(state): delegate to features for constraints

index.bs
Preview at https://api.csswg.org/bikeshed/?url=https://raw.githubusercontent.com/jyasskin/permissions/explicit-settings-object/index.bs#reading-current-states.
I had "A descriptor’s permission state for an optional environment settings object *settings*, defaulting to the current settings object, is …", but I decided the "defaulting" was too ambiguous between setting a default for *settings* vs one for the permission state.
[Web Bluetooth](https://webbluetoothcg.github.io/web-bluetooth/) already passes the settings object explicitly for extra permission data but not for permission state.
=> refactor(permission state): pass the settings object explicitly

index.bs
The old wording implied that the user's response to a prompt always
provided "new information" and so would be likely to affect the
permission state, but that interpretation wasn't intended.
The restriction to the same origin also doesn't match what browsers
actually do, especially with respect to ports, but we should fix that in
a separate change.
Preview at https://api.csswg.org/bikeshed/?url=https://raw.githubusercontent.com/jyasskin/permissions/clarify-request-not-imply-state/index.bs#request-permission-to-use
@jan-ivar
=> fix(request): clarify how requests affect state

index.bs
Preview at https://api.csswg.org/bikeshed/?url=https://raw.githubusercontent.com/jyasskin/permissions/allowed-to-use/index.bs#media-devices.
@foolip, have you considered how "allowed to use" interacts with worker contexts? 
@alvestrand, this touches the spec close to #120 which is still waiting on a link target in [mediacapture-main]. I think it's compatible, but FYI.
Fixes #121
=> refactor(media devices): use "allowed to use"

index.bs
Preview at https://api.csswg.org/bikeshed/?url=https://raw.githubusercontent.com/jyasskin/permissions/object-params/index.bs#permissions-interface.
@tobie, since this is an attempt to bring us into compliance with WebIDL, could you take a look? Is there a better way to call the right part of the "converted to an IDL value" algorithm?
Fixes #59.
=> Pass objects instead of PermissionDescriptors to the Permissions interface.

index.bs
=> Add permission for Accelerometer, Gyroscope, Magnetometer and Orientation Sensor

index.bs
Fix for https://github.com/w3c/mediacapture-main/issues/380 as [discussed at TPAC](https://lists.w3.org/Archives/Public/public-media-capture/2016Oct/0033.html).
In the end, the "stronger than" idea suggested in https://github.com/w3c/mediacapture-main/issues/380#issuecomment-240928800 wasn't flexible enough to describe the relationship between "camera", "microphone", "speakers" and "device-info", so it's spelled out in prose. 
@alvestrand, @fluffy, PTAL.
=> Define restrictions on "device-info" permission (from TPAC).

index.bs
Apply this patch Bikeshed build warnings are history.
=> Link generic sensor permission revocation algorithm and fix note links

index.bs
Add an informative definition for implicit signals.
Fix downstream issue https://github.com/w3c/sensors/issues/211
PTAL @marcoscaceres @mounirlamouri @jyasskin
***
[Preview](https://s3.amazonaws.com/pr-preview/anssiko/permissions/implicit-signals.html) | [Diff](https://s3.amazonaws.com/pr-preview/w3c/permissions/120fe18...anssiko:8fbabc5.html)
=> Clarify "new information about the user’s intent" definition

index.bs
ccf07cf6 broke them while fixing the bikeshed build overall.
=> Fix the links to permissions defined in other specs.

index.bs
They've moved to incubations in https://github.com/jyasskin/permissions-request
and https://github.com/jyasskin/permissions-revoke, which I'll post to WICG once this goes in.
This fixes #46 and fixes #83.
Sorry it took me so long to get around to this. @martinthomson @jan-ivar, did I catch everything you don't want in this spec? @slightlyoff @raymeskhoury @mounirlamouri, did I include everything in the two incubations that you want to see there? (And that was written down at all; they're clearly missing a bunch of examples.)
***
[Preview](https://s3.amazonaws.com/pr-preview/jyasskin/permissions/remove-request-revoke.html) | [Diff](https://s3.amazonaws.com/pr-preview/w3c/permissions/12c9d6a...jyasskin:8d9ae4d.html)
=> Remove permissions.request() and permissions.revoke().

.travis.yml, index.bs
Fixes #24.
Note that we won't get notified if something else breaks around Echidna.
=> chore: make Echidna publication actually work

index.bs
~~(Rendered version available at https://bocoup.github.io/permissions/index.html#automation)~~ Thanks to gh-152, previews are now created automatically
The goal of this patch is to support user-agent automation and application testing for integration with the Permissions API. It's based on [a recent mailing list discussion](http://lists.w3.org/Archives/Public/public-webappsec/2017May/0001.html) and [subsequent "brainstorming"
document](https://docs.google.com/document/d/1Oe4VhgdFnZ6ID3WGyG97n_b1khvYsRcX7T4ddNcyJ9A/edit#heading=h.xws79928vxeg). There, we decided that it would be necessary to simulate user response to "pending" requests from the "request permission to use" and "prompt the user to choose" algorithms. However, the specification does not currently track these requests outside …
=> Introduce "Automation" section

index.bs
The WebDriver specification was recently updated to better-support
extension by web standards [1]. This change allows extension commands to
be defined without a dedicated "name". Because the Automation section
only defines a single command, the name "set" is superfluous. Remove it
in order to expose a more idiomatic HTTP API.
[1] https://github.com/w3c/webdriver/pull/1177
***
<a href="https://pr-preview.s3.amazonaws.com/jugglinmike/permissions/pull/168.html" title="Last updated on Jan 15, 2018, 7:02 PM GMT (af9e221)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/permissions/168/993ab2f...jugglinmike:af9e221.html" title="Last updated on Jan 15, 2018, 7:02 PM GMT (af9e221)">Diff</a>
=> Automation: simplify URI template

index.bs
This adds support for denying access to permissions which are not
allowed in the current context based on an associated Feature Policy.
The Feature Name and Default Allowlist of a policy-controlled feature
must still be declared in the owning spec. This also removes specific
support for the media feature policy which is covered by the more
general support.
***
<a href="https://pr-preview.s3.amazonaws.com/raymeskhoury/permissions/pull/163.html" title="Last updated on Sep 3, 2018, 6:55 AM GMT (e5f7e85)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/permissions/163/eb267d4...raymeskhoury:e5f7e85.html" title="Last updated on Sep 3, 2018, 6:55 AM GMT (e5f7e85)">Diff</a>
=> Add support for permissions that have an associated Feature Policy

index.bs
Similar to background-sync, users will be able to deny background fetches.
***
<a href="https://pr-preview.s3.amazonaws.com/jakearchibald/permissions/pull/183.html" title="Last updated on Sep 14, 2018, 8:34 AM GMT (096436e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/permissions/183/79f9c4e...jakearchibald:096436e.html" title="Last updated on Sep 14, 2018, 8:34 AM GMT (096436e)">Diff</a>
=> Adding background fetch

index.bs
Fix for https://github.com/w3c/permissions/issues/182.
PTAL @raymeskhoury @marcoscaceres
***
<a href="https://pr-preview.s3.amazonaws.com/jan-ivar/permissions/pull/184.html" title="Last updated on Oct 11, 2018, 9:38 PM GMT (c5ac43a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/permissions/184/a58dae5...jan-ivar:c5ac43a.html" title="Last updated on Oct 11, 2018, 9:38 PM GMT (c5ac43a)">Diff</a>
=> Add 'display' permission for screen-capture.

index.bs
To align with https://github.com/w3c/mediacapture-screen-share/pull/87.
***
<a href="https://pr-preview.s3.amazonaws.com/jan-ivar/permissions/pull/188.html" title="Last updated on Dec 31, 2018, 8:19 PM UTC (b2054b9)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/permissions/188/a951a0e...jan-ivar:b2054b9.html" title="Last updated on Dec 31, 2018, 8:19 PM UTC (b2054b9)">Diff</a>
=> Rename 'display' permission to 'display-capture'.

index.bs
The [web-nfc spec]( https://w3c.github.io/web-nfc/ ) defines that UAs should [obtain permissions](https://w3c.github.io/web-nfc/#permissions-and-user-prompts) using Permissions API, but user prompts can be decided by UA policies. 
For example, Chrome team's current stand is summarized [here](https://github.com/chromium/permission.site/pull/61#issuecomment-538391691).
***
<a href="https://pr-preview.s3.amazonaws.com/riju/permissions/pull/201.html" title="Last updated on Oct 10, 2019, 1:42 PM UTC (8745b05)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/permissions/201/ecc3821...riju:8745b05.html" title="Last updated on Oct 10, 2019, 1:42 PM UTC (8745b05)">Diff</a>
=> Add nfc permission.

index.bs
This allows to differentiate between normal camera permissions and
pan-tilt-zoom camera permissions.
In https://github.com/w3ctag/design-reviews/issues/358, TAG wants that there are distinct prompt for camera and pan/tilt/zoom. This CL adds a CameraDevicePermissionDescriptor dictionary so that the normal camera permission can be requested using {name: "camera", panTiltZoom: false} while the pan/tilt/zoom camera permission can be requested using {name: "camera", panTiltZoom: true}.
The CameraDevicePermissionDescriptor can then be referenced by media capture specifications.
***
<a href="https://pr-preview.s3.amazonaws.com/eehakkin/intel-w3c-permissions/pull/204.html" title="Last updated on Mar 20, 2020, 1:34 PM UTC (daadf87)">Preview</a> | <a …
=> Add CameraDevicePermissionDescriptor for 'camera' permission

index.bs
Closes #206 
Also, replaced the "responsible browsing context" while was at it
***
<a href="https://pr-preview.s3.amazonaws.com/yoavweiss/permissions/pull/207.html" title="Last updated on Apr 27, 2020, 7:34 PM UTC (85f963b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/permissions/207/d258783...yoavweiss:85f963b.html" title="Last updated on Apr 27, 2020, 7:34 PM UTC (85f963b)">Diff</a>
=> Export permission task source

index.bs
The [Clipboard API Spec](https://www.w3.org/TR/clipboard-apis/#clipboard-permissions) has had separate `clipboard-read` and `clipboard-write` permissions for a while now, so let's update this spec to mention this. This was mentioned in https://github.com/w3c/permissions/issues/175 as well.
This is my first specification change attempt, so please let me know if there's anything I'm missing. bikeshed spec had no errors when generating this change though.
***
<a href="https://pr-preview.s3.amazonaws.com/dway123/permissions/pull/209.html" title="Last updated on Jun 2, 2020, 11:13 PM UTC (0d78d2f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/permissions/209/9675ebf...dway123:0d78d2f.html" title="Last updated on Jun 2, 2020, 11:13 PM UTC (0d78d2f)">Diff</a>
=> Update clipboard permissions as per Clipboard Specification.

index.bs
The `"speaker"` permission is used by the new [selectAudioOutput](https://w3c.github.io/mediacapture-output/#dom-mediadevices-selectaudiooutput) API, but is being renamed in https://github.com/w3c/mediacapture-output/pull/96 for consistency with the reintroduced permissions policy of the same name. https://github.com/w3c/webappsec-permissions-policy/pull/398
The old name had folks thinking an iframe without `allow="speaker"` would be silent. The new name clarifies the powerful feature in question is instead the ability to request and output to non-default audio output devices.
***
<a href="https://pr-preview.s3.amazonaws.com/jan-ivar/permissions/pull/218.html" title="Last updated on Jul 22, 2020, 12:47 AM UTC (ea5bede)">Preview</a> | <a …
=> Rename "speaker" to "speaker-selection" + media devices are secure context

index.bs
We can `export`, explicitly `noexport`, or remove the `<dfn>`, and I'm not certain which is best. WebDriver itself gets away without making an explicit choice because it has a local use of every endpoint at https://w3c.github.io/webdriver/#endpoints. (and maybe because Respec doesn't have this warning?) I don't see a reason another specification would depend on this, so `noexport` should be fine, but because it's a public API used by tests, `export` seems semantically right, so I went with `export`.
***
<a href="https://pr-preview.s3.amazonaws.com/jyasskin/permissions/pull/216.html" title="Last updated on Jul 23, 2020, 10:34 PM UTC (3db5fbd)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/permissions/216/e38762b...jyasskin:3db5fbd.html" title="Last updated on Jul 23, 2020, …
=> Noexport the "Set Permission" dfn to fix a Bikeshed warning.

index.bs
The other specs must have been cleaned up since this was written.
***
<a href="https://pr-preview.s3.amazonaws.com/jyasskin/permissions/pull/217.html" title="Last updated on Jul 20, 2020, 9:05 PM UTC (8cd398b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/permissions/217/e38762b...jyasskin:8cd398b.html" title="Last updated on Jul 20, 2020, 9:05 PM UTC (8cd398b)">Diff</a>
=> Remove almost all link-defaults.

index.bs
#156 hided PermissionName to fix linking issues but doing so prevents IDL crawlers to collect the type properly. This patch reverts it and instead makes things consistent with other enum values.
See also https://github.com/w3c/webref/issues/47
***
<a href="https://pr-preview.s3.amazonaws.com/saschanaz/permissions/pull/229.html" title="Last updated on Feb 17, 2021, 12:33 AM UTC (cd7f1ad)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/permissions/229/9cbf73c...saschanaz:cd7f1ad.html" title="Last updated on Feb 17, 2021, 12:33 AM UTC (cd7f1ad)">Diff</a>
=> Expose PermissionName as IDL

index.bs
Also WebKit implements these permissions:
https://bugs.webkit.org/show_bug.cgi?id=221399
***
<a href="https://pr-preview.s3.amazonaws.com/anssiko/permissions/pull/232.html" title="Last updated on Mar 25, 2021, 3:03 PM UTC (2de2a13)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/permissions/232/388ee1c...anssiko:2de2a13.html" title="Last updated on Mar 25, 2021, 3:03 PM UTC (2de2a13)">Diff</a>
=> Remove Permission Registry provisional note

index.bs
Counterpart to https://github.com/w3c/mediacapture-main/pull/745 based on https://github.com/w3c/permissions/issues/223#issuecomment-681327793.
***
<a href="https://pr-preview.s3.amazonaws.com/jan-ivar/permissions/pull/225.html" title="Last updated on Jun 3, 2021, 1:22 AM UTC (f005cb1)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/permissions/225/9cbf73c...jan-ivar:f005cb1.html" title="Last updated on Jun 3, 2021, 1:22 AM UTC (f005cb1)">Diff</a>
=> Use media device permission revocation algorithm.

index.bs
The section refers to display-capture, not screen-capture.
***
<a href="https://pr-preview.s3.amazonaws.com/eladalon1983/permissions/pull/252.html" title="Last updated on Jul 21, 2021, 8:34 PM UTC (4fc6204)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/permissions/252/e1f13de...eladalon1983:4fc6204.html" title="Last updated on Jul 21, 2021, 8:34 PM UTC (4fc6204)">Diff</a>
=> s/Screen Capture/Display Capture

index.bs
closes #237
Avoids having to rely on array order to know what a particular permission status belongs to.  
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/permissions/pull/248.html" title="Last updated on Aug 5, 2021, 4:20 AM UTC (5960935)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/permissions/248/f5d8cac...5960935.html" title="Last updated on Aug 5, 2021, 4:20 AM UTC (5960935)">Diff</a>
=> Add name attribute to PermissionStatus

index.bs
Marked all single engine things "at risk".
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/permissions/pull/259.html" title="Last updated on Jul 28, 2021, 9:07 AM UTC (b81c73e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/permissions/259/3af5370...b81c73e.html" title="Last updated on Jul 28, 2021, 9:07 AM UTC (b81c73e)">Diff</a>
=> Editorial: mark various permissions "at risk"

index.html
Renaming the spec, making it more clear what it's actually about. 
Also, this spec is commonly referred to as the "Permissions API" (even thought out the spec).
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/permissions/pull/284.html" title="Last updated on Aug 31, 2021, 5:06 AM UTC (64fe4bc)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/permissions/284/a8d8549...64fe4bc.html" title="Last updated on Aug 31, 2021, 5:06 AM UTC (64fe4bc)">Diff</a>
=> Editorial: rename specification

index.html
***
<a href="https://pr-preview.s3.amazonaws.com/fselcukcan/permissions/pull/290.html" title="Last updated on Aug 31, 2021, 11:31 PM UTC (ca27c30)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/permissions/290/6cac33f...fselcukcan:ca27c30.html" title="Last updated on Aug 31, 2021, 11:31 PM UTC (ca27c30)">Diff</a>
=> Editorial: fixed typos in Permissions Policy section

index.html
closes #309 
We need https://github.com/w3c/ambient-light/pull/70 to land first before we can land this.
***
<a href="https://pr-preview.s3.amazonaws.com/miketaylr/permissions/pull/310.html" title="Last updated on Nov 4, 2021, 1:40 AM UTC (5d6499c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/permissions/310/2dbcd62...miketaylr:5d6499c.html" title="Last updated on Nov 4, 2021, 1:40 AM UTC (5d6499c)">Diff</a>
=> Remove ambient-light-sensor details defined in [[ambient-light]]

index.html
Editorial change... Permission integration is now in the Geolocation spec.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/permissions/pull/311.html" title="Last updated on Nov 4, 2021, 4:24 AM UTC (8d61c91)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/permissions/311/136841b...8d61c91.html" title="Last updated on Nov 4, 2021, 4:24 AM UTC (8d61c91)">Diff</a>
=> Editorial: soft identify geolocation powerful feature

index.html
Add "'getting the current permission state", which is a simpler version of "permission state". 
Also get rid Secure Context check.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/permissions/pull/325.html" title="Last updated on Nov 19, 2021, 1:50 AM UTC (9b6f9d9)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/permissions/325/c3c5605...9b6f9d9.html" title="Last updated on Nov 19, 2021, 1:50 AM UTC (9b6f9d9)">Diff</a>
=> Editorial: Add 'getting the current permission state' steps

index.html
closes #315
There are no longer any powerful features that use this flag (Notifications was the only one, and the 3 major engines removed that feature a few years back).
***
<a href="https://pr-preview.s3.amazonaws.com/miketaylr/permissions/pull/327.html" title="Last updated on Nov 19, 2021, 6:47 PM UTC (e425d01)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/permissions/327/620ad6a...miketaylr:e425d01.html" title="Last updated on Nov 19, 2021, 6:47 PM UTC (e425d01)">Diff</a>
=> Remove the allowed in non-secure contexts flag

index.html
closes #233 
Exports [=permission/lifetimes=].
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/permissions/pull/287.html" title="Last updated on Nov 18, 2021, 8:01 AM UTC (69a5c32)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/permissions/287/c3c5605...69a5c32.html" title="Last updated on Nov 18, 2021, 8:01 AM UTC (69a5c32)">Diff</a>
=> Define permission lifetimes

index.html
=> Editorial: link <a>express permission</a> inside <a>request permission to use</a>.

index.html
The W3C now requires the Priv/Sec guidelines to be split into two sections (and they should be normative!).
Because the two existing paragraphs convey the same information (IMO), I got rid of the first paragraph; I found the second more clear. 
I also added a normative requirement:
> Thus, implementations SHOULD provide  a means for users to control (globally or selectively) the [=permission states=]= of each [=power feature=].
Which is basically "site settings" in various browsers.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/permissions/pull/344.html" title="Last updated on Feb 2, 2022, 1:51 AM UTC (01517f6)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/permissions/344/378b7fd...01517f6.html" title="Last updated on Feb 2, 2022, 1:51 AM UTC (01517f6)">Diff</a>
=> Split Pri/Sec considerations + give user control over features

index.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/permissions/pull/352.html" title="Last updated on Feb 4, 2022, 5:50 AM UTC (15db4ba)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/permissions/352/01ae676...15db4ba.html" title="Last updated on Feb 4, 2022, 5:50 AM UTC (15db4ba)">Diff</a>
=> Editorial: run 'in parallel', not asynchronously

index.html
Tried to clean up some of the definitions. 
Moved lifetimes into the model section. 
Moved "Express permission" into the Permissions section.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/permissions/pull/355.html" title="Last updated on Feb 5, 2022, 1:26 AM UTC (a0e427d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/permissions/355/069b7dd...a0e427d.html" title="Last updated on Feb 5, 2022, 1:26 AM UTC (a0e427d)">Diff</a>
=> Editorial: cleanup Permissions model

index.html
closes #266
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/permissions/pull/360.html" title="Last updated on Feb 9, 2022, 2:43 PM UTC (4452fbc)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/permissions/360/f503804...4452fbc.html" title="Last updated on Feb 9, 2022, 2:43 PM UTC (4452fbc)">Diff</a>
=> Simplify GC model

index.html
Depends on #350, #351, and the actual Powerful Features Registry.
Closes #319
Closes #314 
Closes #263
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/permissions/pull/353.html" title="Last updated on Feb 14, 2022, 6:15 AM UTC (571acf3)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/permissions/353/acd1296...571acf3.html" title="Last updated on Feb 14, 2022, 6:15 AM UTC (571acf3)">Diff</a>
=> Switch PermissionName to DOMString

index.html
Brings back what was originally in the spec.
Blocked on https://github.com/w3c/webdriver/pull/1639
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/permissions/pull/346.html" title="Last updated on Feb 15, 2022, 7:55 AM UTC (32b594a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/permissions/346/7495d07...32b594a.html" title="Last updated on Feb 15, 2022, 7:55 AM UTC (32b594a)">Diff</a>
=> Editorial: bring back Automated Testing into spec

index.html
closes #369
(seems like it was accidentally put in there)
***
<a href="https://pr-preview.s3.amazonaws.com/miketaylr/permissions/pull/370.html" title="Last updated on Mar 2, 2022, 2:28 PM UTC (0130ad7)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/permissions/370/4c4eebc...miketaylr:0130ad7.html" title="Last updated on Mar 2, 2022, 2:28 PM UTC (0130ad7)">Diff</a>
=> Editorial: move [=extra permission data=] out of example

index.html
This appears to have gotten lost in the respec conversion. It's used by https://github.com/WICG/permissions-request/blob/main/index.bs#L91.
***
[PR Preview](https://github.com/tobie/pr-preview#pr-preview) failed to build. _(Last tried on May 3, 2022, 5:42 PM UTC)_.
<details>
<summary>More</summary>
PR Preview relies on a number of web services to run. There seems to be an issue with the following one:
:rotating_light: [Spec Generator](https://www.w3.org/2015/labs/) - Spec Generator is the web service used to build specs that rely on ReSpec.
:link: [Related URL](https://labs.w3.org/spec-generator/?type=respec&url=https%3A%2F%2Fraw.githubusercontent.com%2Fw3c%2Fpermissions%2F2eb7822f40477e653e271e92454c599012c3a99c%2Findex.html%3FisPreview%3Dtrue)
```
📡 HTTP Error 404: …
```
=> editorial: Re-export the default permission query algorithm.

index.html
closes #375
A PR for discussion. PTAL @marcoscaceres
***
[PR Preview](https://github.com/tobie/pr-preview#pr-preview) failed to build. _(Last tried on May 23, 2022, 6:26 PM UTC)_.
<details>
<summary>More</summary>
PR Preview relies on a number of web services to run. There seems to be an issue with the following one:
:rotating_light: [Spec Generator](https://www.w3.org/2015/labs/) - Spec Generator is the web service used to build specs that rely on ReSpec.
:link: [Related URL](https://labs.w3.org/spec-generator/?type=respec&url=https%3A%2F%2Fraw.githubusercontent.com%2Fmiketaylr%2Fpermissions%2Fd0c11a15df5aa76e285cafd1925f2d3c9480b527%2Findex.html%3FisPreview%3Dtrue)
```
📡 HTTP Error 404: http://labs.w3.org/spec-generator/uploads/OUQ0MZ
```
_If you don't have enough information above to …
=> Allow "prompt the user to choose" apply to one or more options.

index.html
I propose to close it as invalid, see https://github.com/w3c/permissions/issues/278#issuecomment-1137774977
closes #278
***
[PR Preview](https://github.com/tobie/pr-preview#pr-preview) failed to build. _(Last tried on May 25, 2022, 7:44 PM UTC)_.
<details>
<summary>More</summary>
PR Preview relies on a number of web services to run. There seems to be an issue with the following one:
:rotating_light: [Spec Generator](https://www.w3.org/2015/labs/) - Spec Generator is the web service used to build specs that rely on ReSpec.
:link: [Related URL](https://labs.w3.org/spec-generator/?type=respec&url=https%3A%2F%2Fraw.githubusercontent.com%2Fmiketaylr%2Fpermissions%2F8a506308fa509f7ee2f133e835445ea07edef900%2Findex.html%3FisPreview%3Dtrue)
```
📡 HTTP Error 404: …
```
=> chore: Remove reference to issue #278

index.html
We already have local-lt="state" for https://w3c.github.io/permissions/#dfn-states, and it seems easier to understand if we explicitly use `<a>permission state</a>`.
***
<a href="https://pr-preview.s3.amazonaws.com/miketaylr/permissions/pull/385.html" title="Last updated on Oct 18, 2022, 1:50 AM UTC (7c01d13)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/permissions/385/698e614...miketaylr:7c01d13.html" title="Last updated on Oct 18, 2022, 1:50 AM UTC (7c01d13)">Diff</a>
=> Meta: remove local-lt for <dfn>permission state<dfn>

index.html
closes #387 
* Realm-based permissions is not implemented by any engine.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/permissions/pull/397.html" title="Last updated on Nov 28, 2022, 11:47 AM UTC (80fca1a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/permissions/397/5fd60ef...80fca1a.html" title="Last updated on Nov 28, 2022, 11:47 AM UTC (80fca1a)">Diff</a>
=> Remove use of realms

index.html
closes #393
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/permissions/pull/398.html" title="Last updated on Dec 8, 2022, 1:03 AM UTC (50f1d85)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/permissions/398/5fd60ef...50f1d85.html" title="Last updated on Dec 8, 2022, 1:03 AM UTC (50f1d85)">Diff</a>
=> Editorial: define and improve use of permissions task source

index.html
closes #403
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/permissions/pull/404.html" title="Last updated on Dec 9, 2022, 1:30 AM UTC (ca78a31)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/permissions/404/5fd60ef...ca78a31.html" title="Last updated on Dec 9, 2022, 1:30 AM UTC (ca78a31)">Diff</a>
=> Editorial: fix PermissionDescriptor name check in query()

index.html
This is a draft attempt at defining a permission store with a couple of questions still to be figured out, some of which are also marked as issues inline. Some high-level thoughts:
- I've so far declared a single global permission store to be maintained by UAs, is that what we were shooting for?
- We should still allow for UAs to have more flexibility in storing smaller-scoped or shorter-lived permissions, e.g. for a single tab. It feels like this needs to be a non-normative note as attempting to specify that might go against the idea that it can be flexible.
- This ignores a lot of details around how we need to cross the process boundary to access permissions, though I've tried to make setting (and removing) permissions an async step.
- As discussed with Anne before, there's the question …
=> Define a permission store (closes #384)

index.html
Used e.g. by https://w3c.github.io/mediacapture-automation/
***
<a href="https://pr-preview.s3.amazonaws.com/dontcallmedom/permissions/pull/408.html" title="Last updated on Dec 15, 2022, 5:52 AM UTC (68b8b9d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/permissions/408/9aaca68...dontcallmedom:68b8b9d.html" title="Last updated on Dec 15, 2022, 5:52 AM UTC (68b8b9d)">Diff</a>
=> Export definition of Set Permission extension command

index.html
***
<a href="https://pr-preview.s3.amazonaws.com/miketaylr/permissions/pull/426.html" title="Last updated on Nov 19, 2023, 10:41 PM UTC (fe16f36)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/permissions/426/f647e6d...miketaylr:fe16f36.html" title="Last updated on Nov 19, 2023, 10:41 PM UTC (fe16f36)">Diff</a>
=> Add Permissions Registry back to main document

index.html
Regex (VSCode):
- from: `<a>(.*?[\s\S\r]*?)</a>`
- to: `[=$1=]`
As per @marcoscaceres's request on https://github.com/w3c/permissions/pull/425.
CC @miketaylr
***
<a href="https://pr-preview.s3.amazonaws.com/thiagowfx/permissions/pull/428.html" title="Last updated on Nov 22, 2023, 1:37 PM UTC (fed8cf4)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/permissions/428/f647e6d...thiagowfx:fed8cf4.html" title="Last updated on Nov 22, 2023, 1:37 PM UTC (fed8cf4)">Diff</a>
=> Editorial: Replace all <a>foo</a> with [=foo=]

index.html
closes #430
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/permissions/pull/432.html" title="Last updated on Dec 1, 2023, 2:00 AM UTC (6b3f7f0)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/permissions/432/aaff51e...6b3f7f0.html" title="Last updated on Dec 1, 2023, 2:00 AM UTC (6b3f7f0)">Diff</a>
=> Editorial: add example of prompt timing out

index.html
Closes #424
Based on https://github.com/w3c/permissions/pull/425 by @thiagowfx
***
<a href="https://pr-preview.s3.amazonaws.com/OrKoN/permissions/pull/431.html" title="Last updated on Dec 8, 2023, 2:22 PM UTC (925957d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/permissions/431/aaff51e...OrKoN:925957d.html" title="Last updated on Dec 8, 2023, 2:22 PM UTC (925957d)">Diff</a>
=> Introduce Browser Permissions for WebDriver BiDi

index.html
It appears that the definition was moved according to https://respec.org/xref/?term=accelerometer&types=_CONCEPT_
***
<a href="https://pr-preview.s3.amazonaws.com/OrKoN/permissions/pull/435.html" title="Last updated on Jan 12, 2024, 3:43 PM UTC (3446e4f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/permissions/435/8094691...OrKoN:3446e4f.html" title="Last updated on Jan 12, 2024, 3:43 PM UTC (3446e4f)">Diff</a>
=> Editorial: Update link to accelerometer permission

index.html
Looks like there was a missing `</div>` in https://github.com/w3c/permissions/pull/431
Also, I applied fixes produced by `HTML Tidy for Apple macOS version 5.9.20`.
***
<a href="https://pr-preview.s3.amazonaws.com/OrKoN/permissions/pull/434.html" title="Last updated on Jan 12, 2024, 4:14 PM UTC (b6c3da9)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/permissions/434/1a263f6...OrKoN:b6c3da9.html" title="Last updated on Jan 12, 2024, 4:14 PM UTC (b6c3da9)">Diff</a>
=> Editorial: fix tidy errors

index.html
In WebDriver classic permissions apply to all enviroments that match the origin of the current environment. In WebDriver BiDi using the current view as an input for commands is not encouraged, therefore, this PR extends the WebDriver BiDi command with an explicit origin parameter.
Closes #424
***
<a href="https://pr-preview.s3.amazonaws.com/OrKoN/permissions/pull/436.html" title="Last updated on Jan 14, 2024, 2:48 PM UTC (2118a06)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/permissions/436/037a40e...OrKoN:2118a06.html" title="Last updated on Jan 14, 2024, 2:48 PM UTC (2118a06)">Diff</a>
=> Require an explicit origin for WebDriver BiDi automation

index.html
closes #440
***
<a href="https://pr-preview.s3.amazonaws.com/saschanaz/permissions/pull/441.html" title="Last updated on Feb 12, 2024, 3:28 PM UTC (79deda5)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/permissions/441/8972985...saschanaz:79deda5.html" title="Last updated on Feb 12, 2024, 3:28 PM UTC (79deda5)">Diff</a>
=> Editorial: Disambiguate `parameters` in Set Permission steps

index.html
And also fixes rootDesc.name use. Failing to convert `descriptor` would throw at a later step but this shouldn't matter as all error types are same.
closes #443
***
<a href="https://pr-preview.s3.amazonaws.com/saschanaz/permissions/pull/444.html" title="Last updated on Feb 14, 2024, 10:20 PM UTC (f0a61b9)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/permissions/444/12a5113...saschanaz:f0a61b9.html" title="Last updated on Feb 14, 2024, 10:20 PM UTC (f0a61b9)">Diff</a>
=> Use `object` for PermissionSetParameters.descriptor

index.html
User contexts in WebDriver BiDi represents the same concepts as the user agents in the infra spec: https://w3c.github.io/webdriver-bidi/#user-contexts According to the infra definition a user agent can be a user profile or a private browsing window.
This PR adds an ability for the automation client to configure which "user agent" should the permissions apply too.
closes #439
***
<a href="https://pr-preview.s3.amazonaws.com/OrKoN/permissions/pull/438.html" title="Last updated on Mar 8, 2024, 6:56 AM UTC (cf691dd)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/permissions/438/75ef57e...OrKoN:cf691dd.html" title="Last updated on Mar 8, 2024, 6:56 AM UTC (cf691dd)">Diff</a>
=> Add userContext field to WebDriver BiDi's setPermission

index.html
***
<a href="https://pr-preview.s3.amazonaws.com/OrKoN/permissions/pull/448.html" title="Last updated on Mar 19, 2024, 10:22 AM UTC (03d16d3)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/permissions/448/645867d...OrKoN:03d16d3.html" title="Last updated on Mar 19, 2024, 10:22 AM UTC (03d16d3)">Diff</a>
=> Editorial: fix wrong cddl syntax used for optionality of the user context

index.html
The spec wrapped the CDDL result type of the Set Permission command in a `<pre class="cddl">` block, even though the return type is actually a reference to a CDDL type defined in WebDriver BiDi.
This update wraps the block into `<code>` instead, following similar conventions used for IDL.
Context for the request is that CDDL definitions defined in specs are now extracted and exposed in Webref to ease validation and integration in tools: https://github.com/w3c/webref/tree/main/ed/cddl
***
<a href="https://pr-preview.s3.amazonaws.com/tidoust/permissions/pull/455.html" title="Last updated on Dec 19, 2024, 8:51 PM UTC (d18fc97)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/permissions/455/4d38a40...tidoust:d18fc97.html" title="Last updated on Dec 19, 2024, 8:51 PM UTC …
=> Use `<code>` for references to a CDDL type

index.html
***
<a href="https://pr-preview.s3.amazonaws.com/saschanaz/permissions/pull/452.html" title="Last updated on Jul 24, 2024, 9:51 PM UTC (62bef90)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/permissions/452/4d38a40...saschanaz:62bef90.html" title="Last updated on Jul 24, 2024, 9:51 PM UTC (62bef90)">Diff</a>
=> Editorial: Fix sentences around permission states

index.html
Fix CDDL attributes. Analogous of https://github.com/w3c/webdriver-bidi/pull/927.
***
<a href="https://pr-preview.s3.amazonaws.com/sadym-chromium/permissions/pull/464.html" title="Last updated on Jun 24, 2025, 10:59 AM UTC (67ab4c0)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/permissions/464/77f8bc7...sadym-chromium:67ab4c0.html" title="Last updated on Jun 24, 2025, 10:59 AM UTC (67ab4c0)">Diff</a>
=> Editorial: Adapt CDDL declarations to new version of Bikeshed

index.html
We previously added topLevelOrigin to setPermission to make it possible to set storage-access and top-level-storage-access permissions (#468). However, for all other permissions, 'origin' is interpreted as the top-level origin. To align with that, 'origin' in the setPermission command should correspond to the top-level (embedding) origin. This change enforces that fact and makes the second origin parameter the embedded (requesting) origin instead. We also need to change the key generation algorithm to reflect this swap of parameters. This way 'origin' has the same meaning regardless of the permission, and we can still use the method to properly set storage-access and top-level-storage-access permissions.
***
<a href="https://pr-preview.s3.amazonaws.com/jalonthomas/permissions/pull/469.html …
=> Use embeddedOrigin instead of topLevelOrigin in setPermission
